class DistributionJob < ApplicationJob
  queue_as :high
  include Workify

  def perform(index)
    if index.match?('/api/ability-scores')
      AbilityScoresJob.perform_later(index)
    elsif index.match?('/api/alignments')
      AlignmentsJob.perform_later(index)
    elsif index.match?('/api/backgrounds')
      BackgroundsJob.perform_later(index)
    elsif index.match?('/api/classes')
      CharacterClassesJob.perform_later(index)
    elsif index.match?('/api/conditions')
      ConditionsJob.perform_later(index)
    elsif index.match?('/api/damage-types')
      DamageTypesJob.perform_later(index)
    elsif index.match?('/api/equipment') && index.match?(/^((?!categories).)*$/)
      EquipmentJob.perform_later(index)
    elsif index.match?('/api/equipment-categories')
      EquipmentCategoriesJob.perform_later(index)
    elsif index.match?('/api/feats')
      FeatsJob.perform_later(index)
    elsif index.match?('/api/features')
      FeaturesJob.perform_later(index)
    elsif index.match?('/api/languages')
      LanguagesJob.perform_later(index)
    elsif index.match?('/api/magic-items')
      MagicItemsJob.perform_later(index)
    elsif index.match?('/api/magic-schools')
      MagicSchoolsJob.perform_later(index)
    elsif index.match?('/api/monsters')
      MonstersJob.perform_later(index)
    elsif index.match?('/api/proficiencies')
      ProficienciesJob.perform_later(index)
    elsif index.match?('/api/races')
      RacesJob.perform_later(index)
    elsif index.match?('/api/rule-sections')
      RuleSectionsJob.perform_later(index)
    elsif index.match?('/api/rules')
      RulesJob.perform_later(index)
    elsif index.match?('/api/skills')
      SkillsJob.perform_later(index)
    elsif index.match?('/api/spells')
      SpellsJob.perform_later(index)
    elsif index.match?('/api/subclasses')
      SubclassesJob.perform_later(index)
    elsif index.match?('/api/subraces')
      SubracesJob.perform_later(index)
    elsif index.match?('/api/traits')
      TraitsJob.perform_later(index)
    elsif index.match?('/api/weapon-properties')
      WeaponPropertiesJob.perform_later(index)
    else
      puts "Job not found"
    end
  end
end
